### ISSUE TITLE
Makefile:112: recipe for target 'rk.bin.gdb' failed

### ISSUE THREAD

**Issue by JeffCarpenter** [rumpkernel/rumprun-baremetal#4]
cc -ffreestanding -nostdlib -o rk.bin.gdb -T arch/i386/kern.ldscript -m32 intr.o kernel.o undefs.o memalloc.o sched.o subr.o rumpuser.o rumpfiber.o rumppci.o arch/i386/locore32.o arch/i386/cpu_sched.o arch/i386/machdep.o libc_errno.o libc_emul.o libc_malloc.o netbsd_init.o app.o -Lrump/lib -Wl,--whole-archive -lrumpdev_virtio_if_vioif -lrumpdev_disk -lrumpdev_virtio_ld -lrumpdev_virtio_viornd -lrumpdev_pci_virtio    -lrumpdev_pci_if_wm -lrumpdev_miiphy -lrumpdev_pci -lrumpnet_config -lrumpnet_netinet -lrumpnet_net -lrumpnet -lrumpdev_bpf  -lrumpdev -lrumpvfs -lrump -Wl,--no-whole-archive -lcrypto -lpthread -lc 
    /usr/bin/ld: skipping incompatible rump/lib/librumpdev_virtio_if_vioif.a when searching for -lrumpdev_virtio_if_vioif
    /usr/bin/ld: cannot find -lrumpdev_virtio_if_vioif
    /usr/bin/ld: skipping incompatible rump/lib/librumpdev_disk.a when searching for -lrumpdev_disk
    /usr/bin/ld: cannot find -lrumpdev_disk
    /usr/bin/ld: skipping incompatible rump/lib/librumpdev_virtio_ld.a when searching for -lrumpdev_virtio_ld
    /usr/bin/ld: cannot find -lrumpdev_virtio_ld
    /usr/bin/ld: skipping incompatible rump/lib/librumpdev_virtio_viornd.a when searching for -lrumpdev_virtio_viornd
    /usr/bin/ld: cannot find -lrumpdev_virtio_viornd
    /usr/bin/ld: skipping incompatible rump/lib/librumpdev_pci_virtio.a when searching for -lrumpdev_pci_virtio
    /usr/bin/ld: cannot find -lrumpdev_pci_virtio
    /usr/bin/ld: skipping incompatible rump/lib/librumpdev_pci_if_wm.a when searching for -lrumpdev_pci_if_wm
    /usr/bin/ld: cannot find -lrumpdev_pci_if_wm
    /usr/bin/ld: skipping incompatible rump/lib/librumpdev_miiphy.a when searching for -lrumpdev_miiphy
    /usr/bin/ld: cannot find -lrumpdev_miiphy
    /usr/bin/ld: skipping incompatible rump/lib/librumpdev_pci.a when searching for -lrumpdev_pci
    /usr/bin/ld: cannot find -lrumpdev_pci
    /usr/bin/ld: skipping incompatible rump/lib/librumpnet_config.a when searching for -lrumpnet_config
    /usr/bin/ld: cannot find -lrumpnet_config
    /usr/bin/ld: skipping incompatible rump/lib/librumpnet_netinet.a when searching for -lrumpnet_netinet
    /usr/bin/ld: cannot find -lrumpnet_netinet
    /usr/bin/ld: skipping incompatible rump/lib/librumpnet_net.a when searching for -lrumpnet_net
    /usr/bin/ld: cannot find -lrumpnet_net
    /usr/bin/ld: skipping incompatible rump/lib/librumpnet.a when searching for -lrumpnet
    /usr/bin/ld: cannot find -lrumpnet
    /usr/bin/ld: skipping incompatible rump/lib/librumpdev_bpf.a when searching for -lrumpdev_bpf
    /usr/bin/ld: cannot find -lrumpdev_bpf
    /usr/bin/ld: skipping incompatible rump/lib/librumpdev.a when searching for -lrumpdev
    /usr/bin/ld: cannot find -lrumpdev
    /usr/bin/ld: skipping incompatible rump/lib/librumpvfs.a when searching for -lrumpvfs
    /usr/bin/ld: cannot find -lrumpvfs
    /usr/bin/ld: skipping incompatible rump/lib/librump.a when searching for -lrump
    /usr/bin/ld: cannot find -lrump
    /usr/bin/ld: skipping incompatible rump/lib/libcrypto.a when searching for -lcrypto
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libcrypto.so when searching for -lcrypto
    /usr/bin/ld: skipping incompatible /lib/../lib/libcrypto.so when searching for -lcrypto
    /usr/bin/ld: skipping incompatible /usr/lib/../lib/libcrypto.so when searching for -lcrypto
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libcrypto.so when searching for -lcrypto
    /usr/bin/ld: cannot find -lcrypto
    /usr/bin/ld: skipping incompatible rump/lib/libpthread.a when searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libpthread.so when searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libpthread.a when searching for -lpthread
    /usr/bin/ld: skipping incompatible /lib/../lib/libpthread.so when searching for -lpthread
    /usr/bin/ld: skipping incompatible /lib/../lib/libpthread.a when searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/../lib/libpthread.so when searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/../lib/libpthread.a when searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libpthread.so when searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libpthread.a when searching for -lpthread
    /usr/bin/ld: cannot find -lpthread
    /usr/bin/ld: skipping incompatible rump/lib/libc.a when searching for -lc
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libc.so when searching for -lc
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libc.a when searching for -lc
    /usr/bin/ld: skipping incompatible /lib/../lib/libc.so when searching for -lc
    /usr/bin/ld: skipping incompatible /lib/../lib/libc.a when searching for -lc
    /usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
    /usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.a when searching for -lc
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libc.so when searching for -lc
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libc.a when searching for -lc
    /usr/bin/ld: cannot find -lc
    collect2: error: ld returned 1 exit status
    Makefile:112: recipe for target 'rk.bin.gdb' failed
    make: *** [rk.bin.gdb] Error 1

See https://gist.github.com/JeffCarpenter/16976ae1c23ef19dccb3 for full buildme.sh output.

**Comment by tombousso** [comment]
My guess is that your `cc` is a 64 bit compiler, try using the i486 compiler that NetBSD built or some other i386 compiler.

**Comment by anttikantee** [comment]
Like @tombousso guessed, 64bit MD code is still missing (nobody just got around to writing it yet), and half of the build system assumes you're doing a 32bit build...

These days you can easily do a full 32bit build with a single command:
`./buildme.sh -- -F ACLFLAGS=-m32`
(see `.travis.yml`)

That isn't very well documented or userfriendly, I know, sorry about that.

**Comment by JeffCarpenter** [comment]
No worries -- I appreciate the help.

Now when I ran that command, it returned the same slew of linker errors again (full output at https://gist.github.com/JeffCarpenter/04072519b461240bce29). The final invocation of GCC was rumptools/bin/x86_64--netbsd-gcc seemed out of place, so I replaced it with rumptools/bin/i486--netbsdelf-gcc, but to no avail.

**Comment by anttikantee** [comment]
Did you run `make distcleanrump` before the second attempt?

**Comment by JeffCarpenter** [comment]
% make distcleanrump
	% ./buildme.sh -- -F ACLFLAGS=-m32

...

	#   install  /home/jeff/src/rumprun-baremetal/rumptools/dest/usr/lib/librumpdev_miiphy.a
	/home/jeff/src/rumprun-baremetal/rumptools/bin/i486--netbsdelf-install -U -c -p -r -o root -g wheel -m 444   librumpdev_miiphy.a /home/jeff/src/rumprun-baremetal/rumptools/dest/usr/lib/librumpdev_miiphy.a
	/bin/sh: rumptools/bin/x86_64--netbsd-gcc: No such file or directory
	Makefile:47: *** only supported target is x86, you have .  Stop.

	>> ./buildme.sh ran successfully

**Comment by anttikantee** [comment]
Do you have any local changes or do you have CC set in the env?  Try

```
git reset --hard
unset CC
make
```

**Comment by JeffCarpenter** [comment]
That did it. Thanks guys.
